data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?", colClasses = c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
data$DateTime <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
subset_data <- subset(data, Date>=as.Date("2007-02-01", format="%Y-%m-%d") & Date<=as.Date("2007-02-02", format="%Y-%m-%d"))
png("plot4.png", width = 480, height = 480)
par(mfcol=c(2,2))
plot(subset_data$DateTime, subset_data$Global_active_power, type = "l", main = NA, xlab = NA, ylab = "Global Active Power")
plot(subset_data$DateTime, subset_data$Sub_metering_1, type = "l", main = NA, xlab = NA, ylab = "Energy sub metering")
lines(subset_data$DateTime, subset_data$Sub_metering_2, col = "red")
lines(subset_data$DateTime, subset_data$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1, 1, 1, 1), bty = "n")
plot(subset_data$DateTime, subset_data$Voltage, type = "l", main = NA, xlab = "datetime", ylab = "Voltage")
plot(subset_data$DateTime, subset_data$Global_reactive_power, type = "l", main = NA, xlab = "datetime", ylab = "Golbal_reactive_power")
dev.off()